topic:
  tracab-01:
    name: tracabgen5_01_raw
    replication-factor: 2
    partitions: 3
  tracab-02:
    name: tracabgen5_02_filter
    replication-factor: 2
    partitions: 3

#filter:
#  # true -> only take frames that are within the phase time (1st phase and 2nd phase)
#  # false -> all frames are taken
#  inPhase: true

spring:
  application:
    name: "tracabgen5-filter"

  kafka:
    bootstrap-servers:
      - kafka-1:19092
      - kafka-2:19093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      # This is the default: log, fail and stop processing records (stop stream)
      default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndFailExceptionHandler
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      # This is the default: log, fail and stop processing records (stop stream)
      default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndFailExceptionHandler
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    streams:
      application-id: ${spring.application.name}
      client-id: ${spring.application.name}-stream
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      # This is the default: log, fail and stop processing records (stop stream)
      default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndFailExceptionHandler
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    # At application startup a missing topic on the broker will not fail the
    # application startup
    properties:
      schema.registry.url: http://schema-registry-1:8081
    listener:
      missing-topics-fatal: false
